# Generated by Django 5.1.6 on 2025-02-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssesmentComponent',
            new_name='AssessmentComponent',
        ),
        migrations.RenameField(
            model_name='performancerecord',
            old_name='assesment_component',
            new_name='assessment_component',
        ),
    ]
