# Generated by Django 5.1.6 on 2025-03-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_participationrecord_alter_assessmentcomponent_weight_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.classroom'),
        ),
        migrations.AddField(
            model_name='participationrecord',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='students.classroom'),
        ),
        migrations.AddField(
            model_name='participationrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='students.student'),
        ),
    ]
