# Generated by Django 5.1.6 on 2025-03-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='predicted_final_exam',
            field=models.FloatField(default=0.0),
        ),
    ]
